versionOverrides:
  - constraint: "~ 1.25"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.25.0
  - constraint: ">= 1.24 < 1.25"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.24.2
  - constraint: ">= 1.23 < 1.24"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.23.3
  - constraint: "~ 1.22"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.22.6
  - constraint: "~ 1.21"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.21.2
  - constraint: "~ 1.20"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.20.0
  - constraint: "~ 1.19"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.19.0
  - constraint: "~ 1.18"
    values:
      cloudControllerManager:
        repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
        tag: v1.18.0

cloudControllerManager:
  repository: rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
  tag: v1.22.3
  nodeSelector: {}
  tolerations: []
  rbac:
    enabled: true
