name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'
    - cron: '30 6 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.INSTALL_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@bf085276cecdb0cc76fbbe0687a5a0e786646936

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@dadce2fda5b23762a9f49d5a23b39a70b60ea8c9
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_REQUIRE_CONFIG: "ignored"
          RENOVATE_USERNAME: "renovate-action[bot]"
          RENOVATE_GIT_AUTHOR: "Renovate Action <118825710+renovate-action[bot]@users.noreply.github.com>"
          RENOVATE_PLATFORM_COMMIT: "true"
          #LOG_LEVEL: "debug"
        with:
          configurationFile: .github/renovate.json
          token: '${{ steps.get_token.outputs.token }}'
