name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: false
        type: boolean

jobs:
  call-workflow:
    uses: sebtestorg2/renovate-config/.github/workflows/renovate.yaml@develop
    with:
      logLevel: ${{ inputs.logLevel }}
      overrideSchedule: ${{ inputs.overrideSchedule }}
    secrets: inherit
